# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  modernadventure.vip:
    site_hosts:
      - canonical: wp-sandbox-1.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: sam@modernadventure.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
      hsts_max_age: 0
    cache:
      enabled: false
    cron_trigger_lottery:
      # cmd: "./bin/wp-all-export-cron-trigger.sh" # the cron tab will set the directory to your site root and then execute this command
      cmd: "wget -q -O – http://wp-sandbox-1.test/?lty_lottery_cron=update" # the cron tab will set the directory to your site root and then execute this command
      hour: "*" # run every hour
      minute: "*/1" # run every minute
